# Generated by Django 6.1.1 on 2026-09-10 21:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('currency', models.CharField(default='XAF', max_length=3, verbose_name='Devise')),
                ('provider', models.CharField(choices=[('CAMPAY', 'Campay')], max_length=20, verbose_name='Fournisseur')),
                ('idempotency_key', models.CharField(max_length=64, unique=True, verbose_name="Clé d'idempotence")),
                ('provider_transaction_id', models.CharField(blank=True, default='', max_length=100, verbose_name='ID Transaction')),
                ('provider_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('status', models.CharField(choices=[('INITIATED', 'Initié'), ('PENDING', 'En attente'), ('PROCESSING', 'En cours'), ('SUCCESS', 'Réussi'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé')], default='INITIATED', max_length=20, verbose_name='Statut')),
                ('status_message', models.TextField(blank=True, verbose_name='Message')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('garage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garages.garage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=40, unique=True, verbose_name='Référence')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant')),
                ('currency', models.CharField(default='XAF', max_length=3, verbose_name='Devise')),
                ('provider', models.CharField(blank=True, max_length=20, verbose_name='Fournisseur')),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('garage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='garages.garage', verbose_name='Garage')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='payments.payment', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Reçu',
                'verbose_name_plural': 'Reçus',
                'ordering': ['-created_at'],
            },
        ),
    ]
