# Generated by Django 6.1.1 on 2026-09-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('PAYUNIT', 'PayUnit')], max_length=20),
        ),
    ]
