# Generated by Django 6.1.1 on 2026-09-13 21:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('role', models.CharField(choices=[('CLIENT', 'Client'), ('GARAGE', 'Gérant garage'), ('VENDEUR', 'Vendeur')], default='CLIENT', max_length=20)),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('quote', models.TextField(verbose_name='Témoignage')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Note sur 5', verbose_name='Note')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Région'),
        ),
    ]
