# Generated by Django 6.1.1 on 2026-09-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testimonial_city_latitude_city_longitude_city_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Témoignage'),
        ),
    ]
