# Generated by Django 6.1.1 on 2026-09-13 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testimonial_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='content',
        ),
    ]
