# Generated by Django 6.1.1 on 2026-09-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu')], default='ACTIVE', max_length=20, verbose_name='Statut du compte'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Utilisateur'), ('CLIENT', 'Client'), ('ADMIN', 'Administrateur'), ('SUPERUSER', 'Super Utilisateur')], default='USER', max_length=20),
        ),
    ]
