# Generated by Django 6.1.1 on 2026-09-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Utilisateur'), ('CLIENT', 'Client'), ('ADMIN', 'Administrateur')], default='USER', max_length=20),
        ),
    ]
