# Generated by Django 6.1.1 on 2026-09-09 21:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('REGISTER', 'Inscription'), ('PASSWORD_CHANGE', 'Changement mot de passe'), ('PROFILE_UPDATE', 'Mise à jour profil'), ('PAYMENT', 'Paiement'), ('REVIEW', 'Avis'), ('SEARCH', 'Recherche')], max_length=30),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notif_type', models.CharField(choices=[('PAYMENT_SUCCESS', 'Paiement réussi'), ('PAYMENT_FAILED', 'Paiement échoué'), ('GARAGE_APPROVED', 'Garage approuvé'), ('GARAGE_REJECTED', 'Garage rejeté'), ('GARAGE_ACTIVATED', 'Garage activé'), ('TICKET_REPLY', 'Réponse au ticket'), ('ADMIN_MESSAGE', "Message de l'administrateur"), ('SYSTEM', 'Système')], max_length=30, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Lien')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
