# Generated by Django 6.1.1 on 2026-09-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('PART', 'Pièce'), ('GARAGE', 'Garage'), ('ORDER', 'Commande'), ('SERVICE', 'Prestation'), ('PLATFORM', 'Plateforme'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Ouvert'), ('IN_PROGRESS', 'En cours'), ('WAITING_CLIENT', 'En attente du client'), ('RESOLVED', 'Résolu'), ('CLOSED', 'Fermé')], default='OPEN', max_length=30),
        ),
    ]
