# Generated by Django 6.1.1 on 2026-09-07 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='catalog.part'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('PART', 'Problème avec une pièce'), ('GARAGE', 'Problème avec un garage'), ('ORDER', 'Problème avec une commande'), ('SERVICE', 'Problème avec une prestation'), ('PLATFORM', 'Problème avec la plateforme'), ('OTHER', 'Autre')], default='OTHER', max_length=30),
        ),
    ]
