# Generated by Django 6.1.1 on 2026-09-09 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_completed_at_order_delivered_at_and_more'),
        ('reviews', '0002_add_unique_order_to_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='orders.order'),
        ),
    ]
