# Generated by Django 6.1.1 on 2026-09-09 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Catégorie')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='Nom de la pièce')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('reference_oem', models.CharField(blank=True, max_length=100, verbose_name='Référence OEM')),
                ('reference_fabricant', models.CharField(blank=True, max_length=100, verbose_name='Référence fabricant')),
                ('condition', models.CharField(choices=[('NEW', 'Neuf'), ('USED', 'Occasion'), ('REFURBISHED', 'Reconditionné')], default='NEW', max_length=20)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Prix')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('stock_status', models.CharField(choices=[('IN_STOCK', 'Disponible'), ('LOW_STOCK', 'Stock faible'), ('OUT_OF_STOCK', 'Indisponible')], default='OUT_OF_STOCK', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='parts/')),
                ('warranty_months', models.PositiveIntegerField(default=0, verbose_name='Garantie (mois)')),
                ('is_active', models.BooleanField(default=True)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Quartier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='catalog.category')),
                ('garage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='garages.garage')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pièce',
                'verbose_name_plural': 'Pièces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='parts/photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.part')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
