# Generated by Django 6.1.1 on 2026-09-09 07:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Marque')),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModelVehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Modèle')),
                ('slug', models.SlugField()),
                ('year_start', models.PositiveIntegerField(blank=True, null=True, verbose_name='Année début')),
                ('year_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='Année fin')),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='vehicles.brand')),
            ],
            options={
                'verbose_name': 'Modèle',
                'verbose_name_plural': 'Modèles',
                'ordering': ['brand', 'name'],
                'unique_together': {('brand', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, help_text='Ex: Ma Corolla', max_length=100, verbose_name='Surnom')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Année')),
                ('engine', models.CharField(blank=True, help_text='Ex: 1.8', max_length=50, verbose_name='Moteur')),
                ('fuel_type', models.CharField(blank=True, choices=[('ESSENCE', 'Essence'), ('DIESEL', 'Diesel'), ('HYBRID', 'Hybride'), ('ELECTRIC', 'Électrique'), ('GPL', 'GPL')], max_length=20)),
                ('transmission', models.CharField(blank=True, choices=[('MANUAL', 'Manuelle'), ('AUTOMATIC', 'Automatique')], max_length=20)),
                ('license_plate', models.CharField(blank=True, max_length=20, verbose_name='Immatriculation')),
                ('vin', models.CharField(blank=True, max_length=17, verbose_name='VIN')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Véhicule principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.brand')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.modelvehicle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
