# Generated by Django 6.1.1 on 2026-09-09 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='expected_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date prévue'),
        ),
        migrations.AddField(
            model_name='order',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('PAID', 'Payée'), ('PROCESSING', 'En préparation'), ('READY', 'Prête'), ('DELIVERED', 'Livrée'), ('RECEIVED', 'Reçue'), ('COMPLETED', 'Terminée'), ('PICKED_UP', 'Retirée'), ('CANCELLED', 'Annulée'), ('REFUNDED', 'Remboursée')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('PAID', 'Payée'), ('PROCESSING', 'En préparation'), ('READY', 'Prête'), ('DELIVERED', 'Livrée'), ('RECEIVED', 'Reçue'), ('COMPLETED', 'Terminée'), ('PICKED_UP', 'Retirée'), ('CANCELLED', 'Annulée'), ('REFUNDED', 'Remboursée')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Opérateur')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_entries', to='orders.order')),
            ],
            options={
                'verbose_name': 'Historique de statut',
                'verbose_name_plural': 'Historique des statuts',
                'ordering': ['-created_at'],
            },
        ),
    ]
