# Generated by Django 6.1.1 on 2026-09-05 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du garage')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Quartier')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='garages/logos/')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='garages/covers/')),
                ('verification_status', models.CharField(choices=[('PENDING', 'En attente'), ('VERIFIED', 'Vérifié'), ('REJECTED', 'Rejeté'), ('SUSPENDED', 'Suspendu')], default='PENDING', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='Heure ouverture')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='Heure fermeture')),
                ('open_weekends', models.BooleanField(default=False, verbose_name='Ouvert le week-end')),
                ('trust_score', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_clients', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Garage',
                'verbose_name_plural': 'Garages',
                'ordering': ['-trust_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GaragePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='garages/photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='garages.garage')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GarageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Service')),
                ('category', models.CharField(choices=[('DIAGNOSTIC', 'Diagnostic'), ('MAINTENANCE', 'Entretien'), ('BRAKES', 'Freinage'), ('ENGINE', 'Moteur'), ('TRANSMISSION', 'Transmission'), ('ELECTRICAL', 'Électrique'), ('SUSPENSION', 'Suspension'), ('EXHAUST', 'Échappement'), ('AIR_CONDITIONING', 'Climatisation'), ('BODYWORK', 'Carrosserie'), ('TIRE', 'Pneumatique'), ('OIL_CHANGE', 'Vidange'), ('OTHER', 'Autre')], default='OTHER', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('price_min', models.DecimalField(blank=True, decimal_places=0, help_text='Prix minimum estimé en FCFA', max_digits=10, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=0, help_text='Prix maximum estimé en FCFA', max_digits=10, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée estimée (minutes)')),
                ('is_active', models.BooleanField(default=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='garages.garage')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GarageVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('IDENTITY', "Pièce d'identité"), ('BUSINESS_LICENSE', 'Registre de commerce'), ('TAX_CERTIFICATE', 'Attestation fiscale'), ('PROFESSIONAL_CARD', 'Carte professionnelle'), ('OTHER', 'Autre')], max_length=30)),
                ('document', models.FileField(upload_to='garages/verifications/')),
                ('is_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='garages.garage')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vérification garage',
                'verbose_name_plural': 'Vérifications garages',
            },
        ),
        migrations.CreateModel(
            name='GarageBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.brand')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='garages.garage')),
            ],
            options={
                'verbose_name': 'Marque prise en charge',
                'verbose_name_plural': 'Marques prises en charge',
                'unique_together': {('garage', 'brand')},
            },
        ),
    ]
