# Generated by Django 6.1.1 on 2026-09-09 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du garage')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('gps_accuracy', models.DecimalField(blank=True, decimal_places=2, help_text="Précision de la position en mètres lors de l'enregistrement", max_digits=8, null=True, verbose_name='Précision GPS (mètres)')),
                ('location_captured_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de capture de la position')),
                ('photo', models.ImageField(blank=True, help_text='Photo réelle du garage (obligatoire)', null=True, upload_to='garages/main/', verbose_name='Photo du garage')),
                ('verification_status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('SUSPENDED', 'Suspendu')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text="Raison du rejet du garage par l'administrateur", verbose_name='Raison du rejet')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('UNAVAILABLE', 'Indisponible')], default='AVAILABLE', max_length=20)),
                ('availability_message', models.CharField(blank=True, max_length=200, verbose_name='Message de disponibilité')),
                ('approval_status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20, verbose_name='Statut de validation')),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Non payé'), ('PENDING', 'En attente de paiement'), ('PAID', 'Payé'), ('FAILED', 'Échec')], default='UNPAID', max_length=20, verbose_name='Statut de paiement')),
                ('activation_status', models.CharField(choices=[('INACTIVE', 'Inactif'), ('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu')], default='INACTIVE', max_length=20, verbose_name="Statut d'activation")),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name="Heure d'ouverture")),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='Heure de fermeture')),
                ('open_weekends', models.BooleanField(default=False, verbose_name='Ouvert le week-end')),
                ('trust_score', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_clients', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garages', to='core.city', verbose_name='Ville')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garages', to='core.neighborhood', verbose_name='Quartier')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Garage',
                'verbose_name_plural': 'Garages',
                'ordering': ['-trust_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GaragePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='garages/photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='garages.garage')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GarageService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Service')),
                ('category', models.CharField(choices=[('DIAGNOSTIC', 'Diagnostic'), ('MAINTENANCE', 'Entretien'), ('BRAKES', 'Freinage'), ('ENGINE', 'Moteur'), ('TRANSMISSION', 'Transmission'), ('ELECTRICAL', 'Électrique'), ('SUSPENSION', 'Suspension'), ('EXHAUST', 'Échappement'), ('AIR_CONDITIONING', 'Climatisation'), ('BODYWORK', 'Carrosserie'), ('TIRE', 'Pneumatique'), ('OIL_CHANGE', 'Vidange'), ('OTHER', 'Autre')], default='OTHER', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('price_min', models.DecimalField(blank=True, decimal_places=0, help_text='Prix minimum estimé en FCFA', max_digits=10, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=0, help_text='Prix maximum estimé en FCFA', max_digits=10, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée estimée (minutes)')),
                ('is_active', models.BooleanField(default=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='garages.garage')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GarageVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('IDENTITY', "Pièce d'identité"), ('BUSINESS_LICENSE', 'Registre de commerce'), ('TAX_CERTIFICATE', 'Attestation fiscale'), ('PROFESSIONAL_CARD', 'Carte professionnelle'), ('GARAGE_PROOF', 'Justificatif du garage'), ('OTHER', 'Autre')], max_length=30)),
                ('document', models.FileField(help_text='PDF ou Word, max 5 Mo', upload_to='garages/verifications/', verbose_name='Document')),
                ('is_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='garages.garage')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vérification garage',
                'verbose_name_plural': 'Vérifications garages',
            },
        ),
        migrations.AddIndex(
            model_name='garage',
            index=models.Index(fields=['verification_status'], name='garages_gar_verific_5e0490_idx'),
        ),
        migrations.AddIndex(
            model_name='garage',
            index=models.Index(fields=['approval_status'], name='garages_gar_approva_e2a4cc_idx'),
        ),
        migrations.AddIndex(
            model_name='garage',
            index=models.Index(fields=['payment_status'], name='garages_gar_payment_f599ca_idx'),
        ),
        migrations.AddIndex(
            model_name='garage',
            index=models.Index(fields=['activation_status'], name='garages_gar_activat_8a0404_idx'),
        ),
        migrations.AddIndex(
            model_name='garage',
            index=models.Index(fields=['availability_status'], name='garages_gar_availab_b2970a_idx'),
        ),
        migrations.AddIndex(
            model_name='garage',
            index=models.Index(fields=['city'], name='garages_gar_city_id_5d61cf_idx'),
        ),
        migrations.AddIndex(
            model_name='garage',
            index=models.Index(fields=['neighborhood'], name='garages_gar_neighbo_157fe3_idx'),
        ),
        migrations.AddIndex(
            model_name='garage',
            index=models.Index(fields=['owner'], name='garages_gar_owner_i_5e77d8_idx'),
        ),
    ]
