# Generated by Django 6.1.1 on 2026-09-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garageservice',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name='garageservice',
            unique_together={('garage', 'slug')},
        ),
    ]
