# Generated by Django 6.1.1 on 2026-09-09 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('garages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='activation_status',
            field=models.CharField(choices=[('INACTIVE', 'Inactif'), ('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu')], default='INACTIVE', max_length=20, verbose_name="Statut d'activation"),
        ),
        migrations.AddField(
            model_name='garage',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20, verbose_name='Statut de validation'),
        ),
        migrations.AddField(
            model_name='garage',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Non payé'), ('PENDING', 'En attente de paiement'), ('PAID', 'Payé'), ('FAILED', 'Échec')], default='UNPAID', max_length=20, verbose_name='Statut de paiement'),
        ),
        migrations.AddIndex(
            model_name='garage',
            index=models.Index(fields=['approval_status'], name='garages_gar_approva_e2a4cc_idx'),
        ),
        migrations.AddIndex(
            model_name='garage',
            index=models.Index(fields=['payment_status'], name='garages_gar_payment_f599ca_idx'),
        ),
        migrations.AddIndex(
            model_name='garage',
            index=models.Index(fields=['activation_status'], name='garages_gar_activat_8a0404_idx'),
        ),
    ]
