# Generated by Django 6.1.1 on 2026-09-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='open_sunday',
            field=models.BooleanField(default=False, verbose_name='Ouvert le dimanche'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='open_weekends',
            field=models.BooleanField(default=False, verbose_name='Ouvert le samedi'),
        ),
    ]
