# Generated by Django 6.1.1 on 2026-09-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='availability_message',
            field=models.CharField(blank=True, max_length=200, verbose_name='Availability message'),
        ),
        migrations.AddField(
            model_name='garage',
            name='availability_status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('CLOSED', 'Closed'), ('TEMPORARY_CLOSED', 'Temporarily Closed')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='garage',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='closing_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Closing time'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='Neighborhood'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='open_weekends',
            field=models.BooleanField(default=False, verbose_name='Open weekends'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='opening_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Opening time'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20),
        ),
    ]
