# Generated by Django 6.1.1 on 2026-09-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0002_garageservice_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Garage', 'verbose_name_plural': 'Garages'},
        ),
        migrations.RemoveField(
            model_name='garage',
            name='total_reviews',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='trust_score',
        ),
    ]
