# Generated by Django 6.1.1 on 2026-09-07 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_city_neighborhood'),
        ('garages', '0002_garage_availability_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garage',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='logo',
        ),
        migrations.AddField(
            model_name='garage',
            name='gps_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Précision de la position en mètres lors de l'enregistrement", max_digits=8, null=True, verbose_name='Précision GPS (mètres)'),
        ),
        migrations.AddField(
            model_name='garage',
            name='location_captured_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de capture de la position'),
        ),
        migrations.AddField(
            model_name='garage',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo réelle du garage (obligatoire)', null=True, upload_to='garages/main/', verbose_name='Photo du garage'),
        ),
        migrations.AddField(
            model_name='garage',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text="Raison du rejet du garage par l'administrateur", verbose_name='Raison du rejet'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='address',
            field=models.TextField(verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='availability_message',
            field=models.CharField(blank=True, max_length=200, verbose_name='Message de disponibilité'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='availability_status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('UNAVAILABLE', 'Indisponible')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='garage',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garages', to='core.city', verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='closing_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de fermeture'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom du garage'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garages', to='core.neighborhood', verbose_name='Quartier'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='open_weekends',
            field=models.BooleanField(default=False, verbose_name='Ouvert le week-end'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='opening_time',
            field=models.TimeField(blank=True, null=True, verbose_name="Heure d'ouverture"),
        ),
        migrations.AlterField(
            model_name='garage',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('SUSPENDED', 'Suspendu')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='garageverification',
            name='document',
            field=models.FileField(help_text='PDF ou Word, max 5 Mo', upload_to='garages/verifications/', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='garageverification',
            name='document_type',
            field=models.CharField(choices=[('IDENTITY', "Pièce d'identité"), ('BUSINESS_LICENSE', 'Registre de commerce'), ('TAX_CERTIFICATE', 'Attestation fiscale'), ('PROFESSIONAL_CARD', 'Carte professionnelle'), ('GARAGE_PROOF', 'Justificatif du garage'), ('OTHER', 'Autre')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='garage',
            index=models.Index(fields=['verification_status'], name='garages_gar_verific_5e0490_idx'),
        ),
        migrations.AddIndex(
            model_name='garage',
            index=models.Index(fields=['availability_status'], name='garages_gar_availab_b2970a_idx'),
        ),
        migrations.AddIndex(
            model_name='garage',
            index=models.Index(fields=['city'], name='garages_gar_city_id_5d61cf_idx'),
        ),
        migrations.AddIndex(
            model_name='garage',
            index=models.Index(fields=['neighborhood'], name='garages_gar_neighbo_157fe3_idx'),
        ),
        migrations.AddIndex(
            model_name='garage',
            index=models.Index(fields=['owner'], name='garages_gar_owner_i_5e77d8_idx'),
        ),
    ]
